[package]
name = "liquidlauncher"
version = "0.1.0"
authors = ["kawaiinekololis <marco@ccbluex.net>", "superblaubeere27"]
edition = "2018"

# Smaller size
[profile.release]
lto = true
codegen-units = 1

[features]
default = ["gui", "cli"]
gui = ["sciter-rs"]
cli = []

[dependencies]
log = "0.4.0"
env_logger = "0.8.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0.40"
thiserror = "1.0"
void = "1"
zip = "0.5.11"
path-absolutize = "3.0.7"
os_info = "3.0"
regex = "1.4.5"
sciter-rs = { version = "0.5.55", optional = true }

# HTTP library
reqwest = { version = "0.11", features = ["json"] }

# Framework for serializing and deserializing data
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"

# We're using Sciter to keep the UI looking the same on every operating system. We could use Ultralight, but we decided to go with Sciter.
# sciter-rs = "0.5.54"

# Not for UI. Just to make downloading our client easy using the integrated operating system browser.
# web-view = "0.7.3"