[package]
name = "liquidlauncher"
version = "0.1.0"
authors = ["kawaiinekololis <marco@ccbluex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
