name: Nix
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build the flake
        run: nix build -L .#liquidlauncher
