name: liquidlauncher

on: [push]

jobs:
  windows:

    runs-on: 
      - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Build UI
        run:
          - cd app
          - npm install
          - npm build

      - name: Download Sciter and extract
        run:
          - wget https://gitlab.com/sciter-engine/sciter-js-sdk/-/archive/main/sciter-js-sdk-main.zip
          - 7z x sciter-js-sdk-main.zip

      - name: Copy into unpacker
        run:
          - cp target/release/liquidlauncher.exe unpacker/data
          - cp sciter-js-sdk-main/bin/windows/x64/sciter.dll unpacker/data
          - mkdir unpacker/data/app
          - cp app/public unpacker/data/app

      - name: Build unpacker
        run:
          - cd unpacker
          - cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: liquidlauncher-barebone
          path: target/release/liquidlauncher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: liquidlauncher-installer
          path: unpacker/target/release/unpacker.exe
